table 'Measure Table'
	lineageTag: 6227aa81-8072-458a-a741-4ec27eb1a841

	measure 'Quanity Sold' = SUM('Sales Data'[OrderQuantity])
		formatString: #,0
		lineageTag: cf327837-00ec-4f07-82c0-90efaedc2f11

	measure 'Quantity Returned' = SUM('Returns Data'[ReturnQuantity])
		formatString: 0
		lineageTag: a96ecaf7-a9b7-491d-adc4-a812463228f5

	measure 'Average Retail Price' = AVERAGE('Product Lookup'[ProductPrice])
		formatString: "₹"\ #,0.###############;#,0.###############\ -"₹";"₹"\ #,0.###############
		lineageTag: e57270e4-7356-4013-9d14-41bc90ecb29c

		annotation PBI_FormatHint = {"currencyCulture":"en-IN"}

	measure 'Total Returns' = COUNT('Returns Data'[ReturnQuantity])
		formatString: #,0
		lineageTag: 362a905d-3826-4cbe-84d2-2e28dd921e37

	measure 'Total Orders' = DISTINCTCOUNT('Sales Data'[OrderNumber])
		formatString: #,0
		lineageTag: fdf3a905-8258-4c58-97af-42a8b7b78b6a

	measure 'Total Customers' =
			
			DISTINCTCOUNT(
			    'Sales Data'[CustomerKey])
		formatString: 0
		lineageTag: f2259240-383a-4bb5-9ed3-cf2654f8feae

	measure 'Return Rate' =
			
			DIVIDE([Quantity Returned],[Quanity Sold],"No Sales")
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 46cdfc18-20c5-4a08-b3b5-308376b1bbfc

	measure 'Bulk Orders' =
			
			CALCULATE(
			    [Total Orders],
			    'Sales Data'[OrderQuantity] > 1
			)
		formatString: 0
		lineageTag: 467d1343-6497-48fc-adff-66c2e5c4f3e1

	measure 'Weekend orders' =
			
			CALCULATE(
			    [Total Orders],
			    'Calendar Lookup'[Weekend] = "Weekend"
			)
		formatString: 0
		lineageTag: 10339c94-d819-40f7-88e9-8a574e746f76

	measure 'Bike Returns' =
			
			CALCULATE(
			    [Total Returns],
			    'Product Categories Lookup'[CategoryName] = "Bikes"
			)
		formatString: 0
		lineageTag: 6d69e9a0-a9bf-469f-967e-43aec881568e

	measure 'Bike Sales' =
			
			CALCULATE(
			    [Quanity Sold],
			    'Product Categories Lookup'[CategoryName] = "Bikes"
			)
		formatString: 0
		lineageTag: 4b29394c-6f50-4a11-98ae-346ea0b7be81

	measure 'Bike Return Rate' =
			
			CALCULATE(
			    [Return Rate],
			    'Product Categories Lookup'[CategoryName] = "Bikes"
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 621aa375-4f5a-41b3-94bf-c52d7ed6818a

	measure 'All Orders' = ```
			
			CALCULATE( 
			    [Total Orders],
			    ALL('Sales Data')
			)
			```
		formatString: 0
		lineageTag: 8f94578f-b5c1-4d7e-9e23-deeb564506ac

	measure '% of All Orders' =
			
			DIVIDE(
			    [Total Orders],
			    [All Orders]
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: ab528e4f-b3c5-4bf5-bb2f-e775387533c9

	measure 'Overall Average Price' =
			
			CALCULATE(
			    [Average Retail Price],
			    ALL(
			        'Product Lookup'
			    )
			)
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 8a3956f2-f3f2-4505-bf1f-8822ebea1588

	measure 'All Returns' =
			
			CALCULATE(
			    [Total Returns],
			    ALL(
			        'Returns Data'
			    )
			)
		formatString: 0
		lineageTag: 54c3323a-0358-4ab6-8cb0-ebc413ca95b8

	measure '% of All Returns' =
			
			DIVIDE(
			    [Total Returns],
			    [All Returns]
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 62244c23-8f1c-4727-b046-6ac491995c67

	measure 'High ticket order' =
			
			CALCULATE(
			    [Total Orders],
			    FILTER(
			        'Product Lookup',
			        'Product Lookup'[ProductPrice] > [Overall Average Price]
			    )
			)
		formatString: 0
		lineageTag: 6438974b-38a7-4090-9102-839d34670125

	measure 'Total Revenue' = ```
			
			SUMX(
			    'Sales Data',
			    'Sales Data'[OrderQuantity] * 
			    RELATED(
			        'Product Lookup'[ProductPrice]
			    )
			)
			```
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 3ac712e4-a702-4627-a8ef-93139c089eea

	measure 'YTD Revenue' =
			
			CALCULATE(
			    [Total Revenue],
			    DATESYTD(
			        'Calendar Lookup'[Date]
			    )
			)
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 624b609a-bae1-464d-a887-38e394e2e2e4

	measure 'Previous Month Revenue' = ```
			
			CALCULATE(
			    [Total Revenue],
			    DATEADD(
			        'Calendar Lookup'[Date],
			        -1,
			        MONTH
			    )
			)
			
			```
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 9df69403-2957-465c-a76c-1247839f2e84

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Revenue Target' =
			
			[Previous Month Revenue] * 1.1
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: a41e03d3-d1fc-4dc5-bb25-56563245aeff

	measure '10-day Rolling Revenue' =
			
			CALCULATE(
			    [Total Revenue],
			    DATESINPERIOD(
			        'Calendar Lookup'[Date],
			        MAX(
			            'Calendar Lookup'[Date]
			        ),
			        -10,
			        DAY
			    )
			)
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: d613d3aa-99be-4b6f-b0a1-b763a3840ccb

	measure 'Total Cost' =
			
			SUMX(
			    'Sales Data',
			    'Sales Data'[OrderQuantity]
			    *
			    RELATED(
			        'Product Lookup'[ProductCost]
			    )
			)
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 1b443c60-b7ff-458e-ae59-9946c7d356fc

	measure 'Total Profit' =
			
			[Total Revenue] - [Total Cost]
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: d9d42ef1-0895-450f-b0b3-fe72ee3decf5

	measure 'Previous Month Profit' =
			
			CALCULATE(
			    [Total Profit],
			    DATEADD(
			        'Calendar Lookup'[Date],
			        -1,
			        MONTH
			    )
			)
		formatString: "₹"\ #,0.###############;#,0.###############\ -"₹";"₹"\ #,0.###############
		lineageTag: 8c77e283-ffc4-4136-9ad3-84e8a049222f

		annotation PBI_FormatHint = {"currencyCulture":"en-IN"}

	measure 'Previous Month Returns' =
			
			CALCULATE(
			    [Total Returns],
			    DATEADD(
			        'Calendar Lookup'[Date],
			        -1,
			        MONTH
			    )
			)
		formatString: 0
		lineageTag: a224289c-3fbe-48d0-8d27-98135f4816c0

	measure 'Previous Month Orders' =
			
			CALCULATE(
			    [Total Orders],
			    DATEADD(
			        'Calendar Lookup'[Date],
			        -1,
			        MONTH
			    )
			)
		formatString: 0
		lineageTag: 86ac08be-03df-4e92-9486-6f22e8b810e6

	measure 'Revenue Target Gap' =
			
			[Total Revenue] - [Revenue Target]
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: f65b2d33-f1f0-4e79-8c22-d75c31a8ed26

	measure 'Profit Target' =
			
			[Previous Month Profit] * 1.1
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 84b331f3-4add-4e0b-956d-dd262bf543c9

	measure 'Profit Target Gap' =
			
			[Total Profit] - [Profit Target]
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 3b219b41-4e96-46f7-aeb7-6386464b730f

	measure 'Order Target' =
			
			[Previous Month Orders] *1.1
		formatString: 0
		lineageTag: f5dcd1d6-17f2-4040-97d8-8ca37197308a

	measure 'Order Target Gap' =
			
			[Total Orders] - [Order Target]
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: c8cf8741-0730-4205-bd6a-a080044ef82b

	measure 'Average Revenue Per Customer' =
			
			DIVIDE(
			    [Total Revenue],
			    [Total Customers]
			)
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: f0232de2-7f67-4fd3-80ca-6c556a0dccab

	measure '90-day Rolling Profit' =
			
			CALCULATE(
			    [Total Profit],
			    DATESINPERIOD(
			        'Calendar Lookup'[Date],
			        LASTDATE(
			            'Calendar Lookup'[Date]
			        ),
			        -90,
			        DAY
			    )
			)
		formatString: "₹"\ #,0;#,0\ -"₹";"₹"\ #,0
		lineageTag: e0b66c60-85cf-4a4d-8b45-064af7b99981

		annotation PBI_FormatHint = {"currencyCulture":"en-IN"}

	measure 'Total Orders (CUstomer details)' =
			
			IF(
			    HASONEVALUE(
			        'Customer Lookup'[CustomerKey]
			    ),
			    [Total Orders],
			    "-"
			)
		formatString: 0
		lineageTag: 407a1bd6-182d-4abf-a627-71dd94d283ca

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Total Revenue (Customer details)' =
			
			IF(
			    HASONEVALUE(
			        'Customer Lookup'[CustomerKey]
			    ),
			    [Total Revenue],
			    "-"
			)
		formatString: \$#,0.0;(\$#,0.0);\$#,0.0
		lineageTag: 58bd2df9-2b23-4b09-91fb-ca9004b00791

	measure 'Adjusted Price' =
			
			[Average Retail Price] * (1 + 'Price Adjustment (%)'[Price Adjustment (%) Value])
		formatString: "₹"\ #,0.###############;#,0.###############\ -"₹";"₹"\ #,0.###############
		lineageTag: 57570a26-b031-4380-86cb-f5989c8e5185

		annotation PBI_FormatHint = {"currencyCulture":"en-IN"}

	measure 'Adjusted Revenue' = ```
			
			SUMX(
			    'Sales Data',
			    'Sales Data'[OrderQuantity] * 
			    [Adjusted Price]
			)
			```
		formatString: "₹"\ #,0.###############;#,0.###############\ -"₹";"₹"\ #,0.###############
		lineageTag: 39dfb5aa-69d4-4fdb-99fe-d58d65a46dc9

		annotation PBI_FormatHint = {"currencyCulture":"en-IN"}

	measure 'Adjusted Profit' =
			
			[Adjusted Revenue] - [Total Cost]
		formatString: "₹"\ #,0.###############;#,0.###############\ -"₹";"₹"\ #,0.###############
		lineageTag: cb2210e2-e210-4b34-986f-44ebf137b9d7

		annotation PBI_FormatHint = {"currencyCulture":"en-IN"}

	measure 'Revenue Target Gap with arrow' =
			
			var upparrow = UNICHAR(129129)
			VAR downarrow = UNICHAR(129131)
			var revenuegap = [Revenue Target Gap]
			RETURN
			IF(revenuegap < 0,
			FORMAT(ROUND(revenuegap,0),"$#,###")&" "& downarrow,
			FORMAT(ROUND(revenuegap,0),"$#,###")&" "& upparrow)
		lineageTag: 048d3efb-10aa-4a6a-bd2b-f0ee6d1aea5e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Revenue Sparkline' = ```
			
			// Static line color - use %23 instead of # for Firefox compatibility (Measure Derived from Eldersveld Modified by Kolosko)
			VAR LineColour = "%2320E2D7"
			VAR PointColour = "%23333333"
			VAR Defs = "<defs> 
			    <linearGradient id='grad' x1='0' y1='25' x2='0' y2='50' gradientUnits='userSpaceOnUse'>
			    <stop stop-color='#20E2D7' offset='0' />
			    <stop stop-color='#20E2D7' offset='0.3' />
			    <stop stop-color='#333333' offset='1' />
			    </linearGradient>
			</defs>"
			// Date field used in this example along the X axis
			VAR XMinDate = MIN('Calendar Lookup'[Start of Month])
			VAR XMaxDate = MAX('Calendar Lookup'[Start of Month])
			 
			// Obtain overall min and overall max measure values when evaluated for each date
			VAR YMinValue = MINX(Values('Calendar Lookup'[Start of Month]),CALCULATE([Total Revenue]))
			VAR YMaxValue = MAXX(Values('Calendar Lookup'[Start of Month]),CALCULATE([Total Revenue]))
			 
			// Build table of X & Y coordinates and fit to 50 x 150 viewbox
			VAR SparklineTable = ADDCOLUMNS(
			    SUMMARIZE('Calendar Lookup','Calendar Lookup'[Start of Month]),
			        "X",INT(150 * DIVIDE('Calendar Lookup'[Start of Month] - XMinDate, XMaxDate - XMinDate)),
			        "Y",INT(50 * DIVIDE([Total Revenue] - YMinValue, YMaxValue - YMinValue)))
			 
			// Concatenate X & Y coordinates to build the sparkline
			VAR Lines = CONCATENATEX(SparklineTable,[X] & "," & 50-[Y]," ", 'Calendar Lookup'[Start of Month])
			 
			//Last data points on the line
			VAR LastSparkYValue = MAXX( FILTER(SparklineTable, 'Calendar Lookup'[Start of Month] = XMaxDate), [Y])
			VAR LastSparkXValue = MAXX( FILTER(SparklineTable, 'Calendar Lookup'[Start of Month] = XMaxDate), [X])
			 
			// Add to SVG, and verify Data Category is set to Image URL for this measure
			VAR SVGImageURL =
			    "data:image/svg+xml;utf8," &
			    --- gradient ---
			    "<svg xmlns='http://www.w3.org/2000/svg' x='0px' y='0px' viewBox='-7 -7 164 64'>" & Defs &
			    "<polyline fill='url(#grad)' fill-opacity='0.3' stroke='transparent'
			     stroke-width='0' points=' 0 50 " & Lines &
			     " 150 150 Z '/>" &
			    --- Lines ---
			    "<polyline
			        fill='transparent' stroke='" & LineColour & "'
			        stroke-linecap='round' stroke-linejoin='round'
			        stroke-width='2' points=' " & Lines &
			    " '/>" & 
			    --- Last Point---
			        "<circle cx='"& LastSparkXValue &  "' cy='" & 50 - LastSparkYValue & "' r='4' stroke='" & LineColour & "' stroke-width='2' fill='" & PointColour & "' />" &
			        "</svg>"
			RETURN SVGImageURL
			```
		lineageTag: aa97b7da-788a-4e62-932f-6bef93ac9876

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure AverageX = AVERAGEX('Sales Data', [Total Cost])
		lineageTag: 9229bf60-ab47-4f60-b363-666b897941aa

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Rankx = RANKX(ALL('Product Lookup'), CALCULATE([Total Revenue]))
		lineageTag: 54659616-3624-494e-bce8-cac6ea8c39fb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Running Total' =
			CALCULATE(
			    [Total Revenue],
			    FILTER(ALL('Calendar Lookup'[Date]), 'Calendar Lookup'[Date] <= MAX('Calendar Lookup'[Date]))
			)
		lineageTag: 9b79831a-b5cd-4463-b378-0e26d9360a4a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'filter measure' =
			CALCULATE([Bike Sales],
			FILTER(ALL('Calendar Lookup'[Date]),'Calendar Lookup'[Date] <= MAX('Calendar Lookup'[Date])))
		formatString: #,0
		lineageTag: 54244f38-d9a9-4ebb-92ba-c051a37dbd0c

		annotation PBI_FormatHint = {"isDecimal":true}

	partition 'Measure Table' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

