table 'Price Adjustment (%)'
	lineageTag: a82cbde9-ff94-45f5-8870-d695e4622646

	measure 'Price Adjustment (%) Value' = SELECTEDVALUE('Price Adjustment (%)'[Price Adjustment (%)], 0)
		lineageTag: 60f0d282-5fe6-4654-acd9-ae58548332ea

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Price Adjustment (%)'
		lineageTag: 84bee0e2-d2c2-4f98-aeda-75251b17deeb
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Price Adjustment (%)' = calculated
		mode: import
		source = GENERATESERIES(-1, 1, 0.1)

	annotation PBI_Id = 354cb343a6d54e138ff7a46105309ae3

